# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LSDTTNetworkTool
                                 A QGIS plugin
 Builds a vectorized drainage network from LSDTopoTools outputs, divided at tributary junctions.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-29
        copyright            : (C) 2022 by MNiMORPH
        email                : mitc0560@umn.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LSDTTNetworkTool class from file LSDTTNetworkTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_lsdtt_network_tool import LSDTTNetworkTool
    return LSDTTNetworkTool(iface)
